version: 2

jobs:
  linux:
    docker:
      - image: codevapor/swift:5.2
    steps:
      - checkout
      - run: swift build --enable-test-discovery
      - run: swift test --enable-test-discovery
      - run: swift build -c release --enable-test-discovery

workflows:
  version: 2
  tests:
    jobs:
      - linux
